esphome:
  name: aeroponica-controller
  friendly_name: Aeroponica-Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1TS2o7dPW5Zp/D56tU0Ej6eYQ+XJpCFv4vn4uRtS8Q4="

ota:
  - platform: esphome
    password: "4419d1abf17b27227480e3aefc6dea43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aeroponica-Controller"
    password: "Smr1a5L9tYEg"

captive_portal:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO19

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600

# Current sensors/switches/capability set:
# 1. Drain solenoid - Drains nutrient from circulation loop to waste
# 2. Fill solenoid - Adds fresh water to circulation loop to nutrient tank
# 3. Nutrient temperature sensor - Temperature of the nutrient flowing thru circulation loop
# 4. Pre-filter pressure sensor - Pressure of the circulation loop just before the filter
# 5. Circulation loop pressure sensor - Pressure of the circulation loop just before return to nutrient tank
# 6. Pressure loop pressure sensor - Pressure of the nutrient in the pressure loop
# 7. Circulation loop flow sensor - Volume of nutrient flowing in the circulation loop
# 8. Pressure loop flow sensor - Volume of nutrient flowing in the pressure loop out to the plants
# 9. Ultrasonic distance sensor - Level/amount of nutrient in the nutrient tank


###############################
## Switches
###############################
switch:
    # Drain solenoid
  - platform: gpio
    pin: GPIO32
    name: "Drain solenoid"
    id: drainSolenoid
    icon: mdi:icon7-level-up

    # Fill solenoid
  - platform: gpio
    pin: GPIO33
    name: "Fill solenoid"
    id: fillSolenoid
    icon: mdi:icon7-level-up
 
    # Unused
  - platform: gpio
    pin: GPIO25
    name: "Unused 3"
    id: unused3
    internal: true

    # Unused
  - platform: gpio
    pin: GPIO26
    name: "Unused 4"
    id: unused4
    internal: true

    # Unused
  - platform: gpio
    pin: GPIO27
    name: "Unused 5"
    id: unused5
    internal: true

    # Unused
  - platform: gpio
    pin: GPIO14
    name: "Unused 6"
    id: unused6
    internal: true

    # Unused
  - platform: gpio
    pin: GPIO12
    name: "Unused 7"
    id: unused7
    internal: true

    # Unused
  - platform: gpio
    pin: GPIO13
    name: "Unused 8"
    id: unused8
    internal: true

sensor:
    # Temperature probe:
  - platform: dallas_temp
    address: 0xd7011452dd22aa28 
    id: nutrientTemperatureCelsius
    name: "Nutrient Temperature (C)"
    update_interval: 60s
    unit_of_measurement: "°C"
    icon: mdi:icon7-sun-fill

    # Temperature probe (converted to F)
  - platform: template
    id: nutrientTemperatureFahrenheit
    name: "Nutrient Temperature (F)"
    lambda: return id(nutrientTemperatureCelsius).state * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    update_interval: 60s
    icon: mdi:icon7-sun-fill    

    # JSN-SR04T Waterproof distance sensor
  - platform: "jsn_sr04t"
    name: "Nutrient Tank Fill Distance"
    update_interval: 1s    

