esphome:
  name: aeroponica-controller
  friendly_name: Aeroponica-Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1TS2o7dPW5Zp/D56tU0Ej6eYQ+XJpCFv4vn4uRtS8Q4="

ota:
  - platform: esphome
    password: "4419d1abf17b27227480e3aefc6dea43"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aeroponica-Controller"
    password: "Smr1a5L9tYEg"

captive_portal:

web_server:
  port: 80


###############################
## Switches
###############################
switch:
  - platform: gpio
    pin: GPIO32
    name: "Line 1 Feeder"
    id: line_1_feeder

  - platform: gpio
    pin: GPIO33
    name: "Line 2 Feeder"
    id: line_2_feeder
 

  - platform: gpio
    pin: GPIO25
    name: "Line 3 Feeder"
    id: line_3_feeder


  - platform: gpio
    pin: GPIO26
    name: "Line 4 Feeder"
    id: line_4_feeder


  - platform: gpio
    pin: GPIO27
    name: "Line 5 Feeder"
    id: line_5_feeder


  - platform: gpio
    pin: GPIO14
    name: "Line 6 Feeder"
    id: line_6_feeder


  - platform: gpio
    pin: GPIO12
    name: "Line 7 Feeder"
    id: line_7_feeder


  - platform: gpio
    pin: GPIO13
    name: "Line 8 Feeder"
    id: line_8_feeder
