packages:
  device_base: !include
    file: ../common/esp322ChannelRelayBoard.yml
    vars:
      NAME: aeroponica
      FRIENDLY_NAME: Aeroponica
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "hpXN+rXUDSLWGcobsuXwhxTEm5gOzXQ8+giugMVABv8="
      OTA_PASSWORD: "7d111d45dbb313c5e9b70879d0682d71"
      FALLBACK_HOTSPOT_PASSWORD: "UhtYT6DWw17v"
  yamlVersion: !include
    file: ../common/yamlVersion.yml
    vars:
      YAML_VERSION: "v0.0.2 Dec 15, 2024 16:35 pm"
  heartbeat: !include
    file: ../common/heartbeat.yml
    vars:
      LED_GPIO: GPIO23

logger:
  logs:
    sensor: error
    dallas.temp.sensor: error
    pulse_counter: error

one_wire:
  - platform: gpio
    pin: GPIO0

switch:
- platform: gpio
  pin: GPIO16
  id: DrainRelay
  name: Drain

- platform: gpio
  pin: GPIO17
  id: FillRelay
  name: Fill

sensor:
   # pressureLoopFlowRate: Pressure loop flow sensor measures how much nutrient is flowing out to the wall from the pressure loop. Should match the 
   # feed flow sensor on each wall, and only show a value when the lines on each wall are feeding.
  - platform: pulse_counter
    id: pressureLoopFlowRate
    name: "Flow Rate (Pressure Loop)"
    state_class: measurement
    pin: 
        number: GPIO32
    update_interval: 2s
    filters:
      - round: 2
      - lambda: return ((x / 38.0) / 60);
    unit_of_measurement: "L/m"

    # circulationLoopFlowRate: Measures the nutrient flowing in the circulation loop. Should be relatively constant most times, when only the
    # circulation pump is running (it is always running except during maintenance). Should go up significantly when the boost pump is turned on.
  - platform: pulse_counter
    id: circulationLoopFlowRate
    name: "Flow Rate (Circulation Loop)"
    state_class: measurement
    pin: 
        number: GPIO26
    update_interval: 2s
    filters:
      - round: 2
      - lambda: return ((x / 38.0) / 60);
    unit_of_measurement: "L/m" 

  - platform: adc
    pin: GPIO33
    name: "Tank Pressure"
    update_interval: 2s

    # Temperature probe:
  - platform: dallas_temp
    id: nutrientTemperatureCelsius
    name: "Nutrient Temperature (C)"
    update_interval: 10s
    unit_of_measurement: "°C"
    icon: mdi:icon7-sun-fill

    # Temperature probe (converted to F)
  - platform: template
    id: nutrientTemperatureFahrenheit
    name: "Nutrient Temperature (F)"
    lambda: return id(nutrientTemperatureCelsius).state * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    update_interval: 10s
    icon: mdi:icon7-sun-fill    

number:
  - platform: template
    name: Over Temp Threshold # The temp at which the platform will send an over temp theshold event. 
    id: overTempThreshold
    min_value: 1.0
    max_value: 100.0
    initial_value: 62.0
    step: .1
    optimistic: true
    mode: BOX
  - platform: template
    name: Under Temp Threshold # The temp at which the platform will send an under temp theshold event.
    id: underTempThreshold
    min_value: 1.0
    max_value: 100.0
    initial_value: 56.0
    step: .1
    optimistic: true
    mode: BOX