packages:
  device_base: !include
    file: ../common/esp322ChannelRelayBoard.yml
    vars:
      NAME: aeroponica
      FRIENDLY_NAME: Aeroponica
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "hpXN+rXUDSLWGcobsuXwhxTEm5gOzXQ8+giugMVABv8="
      OTA_PASSWORD: "7d111d45dbb313c5e9b70879d0682d71"
      FALLBACK_HOTSPOT_PASSWORD: "UhtYT6DWw17v"
  yamlVersion: !include
    file: ../common/yamlVersion.yml
    vars:
      YAML_VERSION: "v0.0.1 Dec 8, 2024 20:20pm"
  heartbeat: !include
    file: ../common/heartbeat.yml
    vars:
      LED_GPIO: GPIO23

logger:
  logs:
    sensor: error
    pulse_counter: error

switch:
- platform: gpio
  pin: GPIO16
  id: DrainRelay
  name: Drain

- platform: gpio
  pin: GPIO17
  id: FillRelay
  name: Fill

sensor:
   # pressureLoopFlowRate: Pressure loop flow sensor measures how much nutrient is flowing out to the wall from the pressure loop. Should match the 
   # feed flow sensor on each wall, and only show a value when the lines on each wall are feeding.
  - platform: pulse_counter
    id: pressureLoopFlowRate
    name: "Flow Rate (Pressure Loop)"
    state_class: measurement
    pin: 
        number: GPIO32
    update_interval: 2s
    filters:
      - round: 2
      - lambda: return ((x / 38.0) / 60);
    unit_of_measurement: "L/m"

    # circulationLoopFlowRate: Measures the nutrient flowing in the circulation loop. Should be relatively constant most times, when only the
    # circulation pump is running (it is always running except during maintenance). Should go up significantly when the boost pump is turned on.
  - platform: pulse_counter
    id: circulationLoopFlowRate
    name: "Flow Rate (Circulation Loop)"
    state_class: measurement
    pin: 
        number: GPIO35
    update_interval: 2s
    filters:
      - round: 2
      - lambda: return ((x / 38.0) / 60);
    unit_of_measurement: "L/m" 

  - platform: adc
    pin: GPIO25
    name: "Tank Pressure"
    update_interval: 2s