substitutions:
  encryptionKey: "hpXN+rXUDSLWGcobsuXwhxTEm5gOzXQ8+giugMVABv8="
  otaPassword: "7d111d45dbb313c5e9b70879d0682d71"
  fallbackHotspotPassword: "UhtYT6DWw17v"
  yamlVersion: "v .0.1 Dec 8, 2024 15:45"

packages:
  remote_package:
    url: https://github.com/HeathersZen/Aeroponica
    refresh: 0s
    files:
      - esphome/components/aeroponica/aeroponica.yml