packages:
  device_base: !include
    file: ../common/esp322ChannelRelayBoard.yml
    vars:
      NAME: aeroponica
      FRIENDLY_NAME: Aeroponica
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "hpXN+rXUDSLWGcobsuXwhxTEm5gOzXQ8+giugMVABv8="
      OTA_PASSWORD: "7d111d45dbb313c5e9b70879d0682d71"
      FALLBACK_HOTSPOT_PASSWORD: "UhtYT6DWw17v"
  yamlVersion: !include
    file: ../common/yamlVersion.yml
    vars:
      YAML_VERSION: "v0.0.1 Dec 8, 2024 19:45pm"
  heartbeat: !include
    file: ../common/heartbeat.yml
    vars:
      LED_GPIO: GPIO23


  switch:
  - platform: gpio
    pin: GPIO16
    id: DrainRelay
    name: Drain

  - platform: gpio
    pin: GPIO17
    id: FillRelay
    name: Fill