# This YAML is meant to manage all of the sensors in Aeroponica in a single ESP32.
# Very much under development.
# When complete, it should manage all aspects, including:
# Sensors: Flow sensors, Pressure sensors, temperature, ph, EC, ORP, etc.
# Power/solenoids: Fill solenoid, drain solenoid, chiller, Aquatec pump, Growee, circulation pump, boost pump, etc.
# UPS: Monitor the UPS status via USB
# Human interface: Buttons for fill/drain, LEDs to indicate status, pressure gauges, etc.
esphome:
  name: aeroponica-controller
  friendly_name: Aeroponica-Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "${encryptionKey}"

ota:
  - platform: esphome
    password: "${otaPassword}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aeroponica-Controller"
    password: "${fallbackHotspotPassword}"

captive_portal:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO19


# Current sensors/switches/capability set:
# 1. Drain solenoid - Drains nutrient from circulation loop to waste
# 2. Fill solenoid - Adds fresh water to circulation loop to nutrient tank
# 3. Nutrient temperature sensor - Temperature of the nutrient flowing thru circulation loop
# 4. Pre-filter pressure sensor - Pressure of the circulation loop just before the filter
# 5. Circulation loop pressure sensor - Pressure of the circulation loop just before return to nutrient tank
# 6. Pressure loop pressure sensor - Pressure of the nutrient in the pressure loop
# 7. Circulation loop flow sensor - Volume of nutrient flowing in the circulation loop
# 8. Pressure loop flow sensor - Volume of nutrient flowing in the pressure loop out to the plants
# 9. Ultrasonic distance sensor - Level/amount of nutrient in the nutrient tank


###############################
## Switches
###############################
switch:
    # Drain solenoid
  - platform: gpio
    pin: ${drainSolenoidGpio}
    name: "Drain solenoid"
    id: drainSolenoid
    icon: mdi:icon7-level-up

    # Fill solenoid
  - platform: gpio
    pin: ${fillSolenoidGpio}
    name: "Fill solenoid"
    id: fillSolenoid
    icon: mdi:icon7-level-up

  - platform: gpio
    pin: ${ledGpio}
    id: LED
    name: LED
    inverted: True
    internal: True
    restore_mode: RESTORE_DEFAULT_OFF

    #<<: !include "../common/ledSwitch.yml"


sensor:
  #   # Temperature probe:
  # - platform: dallas_temp
  #   address: 0xd7011452dd22aa28 
  #   id: nutrientTemperatureCelsius
  #   name: "Nutrient Temperature (C)"
  #   update_interval: 60s
  #   unit_of_measurement: "°C"
  #   icon: mdi:icon7-sun-fill

  #   # Temperature probe (converted to F)
  # - platform: template
  #   id: nutrientTemperatureFahrenheit
  #   name: "Nutrient Temperature (F)"
  #   lambda: return id(nutrientTemperatureCelsius).state * (9.0/5.0) + 32.0;
  #   unit_of_measurement: "°F"
  #   update_interval: 60s
  #   icon: mdi:icon7-sun-fill    

text_sensor:
  <<: !include "../common/yamlVersion.yml"