esphome:
  name: lolins2mini
  friendly_name: LolinS2Mini

esp32:
  board: lolin_s2_mini #Pinout: https://www.wemos.cc/en/latest/s2/s2_mini.html
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "u9hvZhLi8IDiZRlgH+FwyEp6prwrvfq73WBxaO3WLXc="

ota:
  - platform: esphome
    password: "66d4bbe4e97c001949df2869b872837a"

web_server:
  port: 80

# one_wire:
#   - platform: gpio
#     pin: GPIO33

# uart:
#   tx_pin: GPIO01
#   rx_pin: GPIO03
#   baud_rate: 9600
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lolins2Mini Fallback Hotspot"
    password: "jGQNsO83F477"

captive_portal:
  
sensor:
  #   # Temperature probe:
  # - platform: dallas_temp
  #   address: 0xd7011452dd22aa28 
  #   id: nutrientTemperatureCelsius
  #   name: "Nutrient Temperature (C)"
  #   update_interval: 60s
  #   unit_of_measurement: "°C"
  #   icon: mdi:icon7-sun-fill

  #   # Temperature probe (converted to F)
  # - platform: template
  #   id: nutrientTemperatureFahrenheit
  #   name: "Nutrient Temperature (F)"
  #   lambda: return id(nutrientTemperatureCelsius).state * (9.0/5.0) + 32.0;
  #   unit_of_measurement: "°F"
  #   update_interval: 60s
  #   icon: mdi:icon7-sun-fill    

  #   # JSN-SR04T Waterproof distance sensor
  # - platform: "jsn_sr04t"
  #   id: "Distance"
  #   name: "Distance"
  #   update_interval: 1s
  #   model: "jsn_sr04t"
  #   unit_of_measurement: "cm"
  #   device_class: "distance"
  #   state_class: "MEASUREMENT"

 # returnFlowRate: Return flow sensor measures how much the L/m speed of nutrients flowing back into the reservoir.
  - platform: pulse_counter
    id: flowRateReturn
    name: "Flow Rate (Return)"
    state_class: measurement
    pin: GPIO34
    update_interval: 1000ms
    filters:
      - round: 2
      - lambda: return ((x / 38.0) / 60);
    unit_of_measurement: "L/h"     

switch:
  - platform: gpio
    pin: 15
    id: OnboardLed
    name: OnboardLed
