esphome:
  name: ${NAME}
  friendly_name: ${FRIENDLY_NAME}
  on_boot:
    priority: 800.0
    then:
      lambda: |-
        uartSetPins(0, 44, 43, -1, -1);  

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

api:
  encryption:
    key: ${ENCRYPTION_KEY}

ota:
- platform: esphome
  password: "${OTA_PASSWORD}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${FRIENDLY_NAME} Fallback
    password: "{$FALLBACK_HOTSPOT_PASSWORD}"

captive_portal:

logger:
  level: ${LOG_LEVEL}
  baud_rate: 115200
  hardware_uart: UART0

web_server:
  port: 80

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor

time:
  - platform: sntp
    id: bootTimestamp

button:
  - platform: restart
    name: "Restart"

text_sensor:
  - platform: template
    id: bootTime
    name: "Boot Time"
    lambda: |-
      char str[17];
      auto time = id(bootTime).state;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", time);
      return  { str }; 