switch:
  - platform: template
    name: Fast Update Mode
    id: isFastUpdateModeActive
    restore_mode: RESTORE_DEFAULT_OFF
    assumed_state: false
    optimistic: true


# number:
#     # How often should the update interval happen when Fast Update Mode is active.
#   - platform: template
#     name: Fast Update Interval
#     id: fastUpdateInterval
#     icon: mdi:clock-time-eight-outline
#     initial_value: 5
#     min_value: .5
#     max_value: 10000
#     step: .1
#     optimistic: true
#     mode: BOX                                                                                                                                                 
                                                                                                                                          
