esphome:
  name: ${NAME}
  friendly_name: ${FRIENDLY_NAME}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended

api:
  encryption:
    key: ${ENCRYPTION_KEY}

ota:
  password: "${OTA_PASSWORD}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${FRIENDLY_NAME} Fallback Hotspot
    password: "{$FALLBACK_HOTSPOT_PASSWORD}"

captive_portal:

logger:
  level: ${LOG_LEVEL}