esphome:
  name: ${NAME}
  friendly_name: ${FRIENDLY_NAME}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended

api:
  encryption:
    key: ${ENCRYPTION_KEY}

ota:
- platform: esphome
  password: "${OTA_PASSWORD}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${FRIENDLY_NAME} Fallback Hotspot
    password: "{$FALLBACK_HOTSPOT_PASSWORD}"

captive_portal:

logger:
  level: ${LOG_LEVEL}

web_server:
  port: 80

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime Sensor

time:
  - platform: sntp
    id: bootTimestamp

text_sensor:
  - platform: template
    id: bootTime
    name: "Boot Time"
    lambda: |-
      char str[17];
      auto time = id(bootTime).now();
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", time);
      return  { str }; 