esphome:
  name: ${NAME}
  friendly_name: ${FRIENDLY_NAME}

esp8266:
  board: esp01_1m

api:
  encryption:
    key: ${ENCRYPTION_KEY}

ota:
- platform: esphome
  password: "${OTA_PASSWORD}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${FRIENDLY_NAME} FHS
    password: "{$FALLBACK_HOTSPOT_PASSWORD}"

captive_portal:

logger:
  level: ${LOG_LEVEL}

web_server:
  port: 80