packages:
  yamlVersion: !include
    file: ../common/yamlVersion.yml
    vars:
      YAML_VERSION: "v0.0.2 Dec 15, 2024 16:18 pm"
  heartbeat: !include
    file: ../common/heartbeat.yml
    vars:
      LED_GPIO: GPIO2

esphome:
  name: "system4-thp-sensor"
  friendly_name: system4-thp-sensor

external_components:
  - source: github://TheStaticTurtle/esphome_syslog
    components: [syslog]

syslog:
    ip_address: "sunnyslope.grafana.net"
    port: 514

# Enable logging
logger:
  level: INFO
  
esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "czhoVjNvAL45QTYr9dPGNpYZ5rM8X66JAs5opv4f89E="

ota:
  - platform: esphome
    password: "dd7adf95aa5a34e92677177dae6487fd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ambientdht22-1 Fallback Hotspot"
    password: "R9dbW0nldQ7y"

web_server:
  port: 80

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      id: "system4_temperature"
    pressure:
      name: "BME280 Pressure"
      id: "system4_pressure"
    humidity:
      name: "BME280 Humidity"
      id: "system4_humidity"
  - platform: template
    id: system4_temperatureF
    name: "Temperature (F)"
    lambda: return id(system4_temperature).state * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    update_interval: 60s
    icon: mdi:icon7-sun-fill  
captive_portal:
