esphome:
  name: "w2l1-feed-controller"
  friendly_name: W2L1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BIGYKjB80JAdhPr5zLIvDAhDEws4ltuZ+Pn4QXifujM="

ota:
  - platform: esphome
    password: "0ec517d20576e2c90f4f23b550bd365f"

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "W1L1-Controller Fallback Hotspot"
    password: "0b2K6ulVr72K"

captive_portal:

switch:
  - platform: gpio
    pin: 0
    id: Mister
    icon: "mdi:sprinkler-fire"
    name: Mister
    inverted: yes
    restore_mode: RESTORE_DEFAULT_OFF        

interval:
  - interval: 5min
    then:
      - switch.turn_on: Mister
      - delay: "00:00:06"
      - switch.turn_off: Mister