substitutions:
  NAME: w3l1controller
  FRIENDLY_NAME: "W3L1 Controller"

packages:
  device_base: !include
    file: ../common/boards/esp322ChannelRelayBoard.yml
    vars:
      NAME: ${NAME}
      FRIENDLY_NAME: ${FRIENDLY_NAME}
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "eghKGz0oPMDGTfFYFgaxw3iUBAujxUQbTr0KPBEAwwY="
      OTA_PASSWORD: "805de5af4da0cd679cb7e0090cd4ad50"
      FALLBACK_HOTSPOT_PASSWORD: "JP2dIejjuZTD"
  yamlVersion: !include
    file: ../common/sensors/yamlVersion.yml
    vars:
      YAML_VERSION: "v1.0.0 Jan 31, 2025 19:48"
  heartbeat: !include
    file: ../common/scripts/heartbeat.yml
    vars:
      LED_GPIO: GPIO2
      LED_INVERTED: true
  wifiSignal: !include
    file: ../common/sensors/wifiSignal.yml
  repeatingRelayTimer: !include
    file: ../common/subcomponents/repeatingRelayTimer.yml
    vars:
      NAME: ${NAME}
      FRIENDLY_NAME: ${FRIENDLY_NAME}
      RELAY_GPIO: GPIO16
      RELAY_NAME: "Feeder"
      RELAY_ID: "feeder"
      RELAY_ON_DURATION_NAME: "Feed - Feed Duration"
      RELAY_ON_DURATION_ID: "feedRelayOnDuration"
      RELAY_ON_INITIAL_VALUE: 2.5
      PAUSE_DURATION_NAME: "Feed - Rest Duration"
      PAUSE_DURATION_ID: "feedPauseDuration"
      PAUSE_DURATION_INITIAL_VALUE: 300
      NEXT_EVENT_COUNTDOWN_NAME: "Feed - Next Feed Countdown"
      NEXT_EVENT_COUNTDOWN_ID: "feedNextOnEventCountdown"
  repeatingRelayTimer2: !include
    file: ../common/subcomponents/repeatingRelayTimer.yml
    vars:
      NAME: ${NAME}
      FRIENDLY_NAME: ${FRIENDLY_NAME}
      RELAY_GPIO: GPIO17
      RELAY_NAME: "Drain"
      RELAY_ID: "drain"
      RELAY_ON_DURATION_NAME: "Drain - Drain Duration"
      RELAY_ON_DURATION_ID: "drainRelayOnDuration"
      RELAY_ON_INITIAL_VALUE: 6
      PAUSE_DURATION_NAME: "Drain - Rest Duration"
      PAUSE_DURATION_ID: "relayPauseDuration"
      PAUSE_DURATION_INITIAL_VALUE: 467
      NEXT_EVENT_COUNTDOWN_NAME: "Drain - Next Drain Countdown"
      NEXT_EVENT_COUNTDOWN_ID: "relayNextOnEventCountdown"

# Enable logging
logger:
  baud_rate: 0
  logs:
    uart: ERROR
    logger: ERROR
    sensor: ERROR
    uart_debug: ERROR
    text_sensor: ERROR
    number: ERROR

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Los_Angeles
