packages:
  device_base: !include
    file: ../common/boards/esp322ChannelRelayBoard.yml
    vars:
      NAME: w3l1-controller
      FRIENDLY_NAME: "W3L1 Controller"
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "eghKGz0oPMDGTfFYFgaxw3iUBAujxUQbTr0KPBEAwwY="
      OTA_PASSWORD: "805de5af4da0cd679cb7e0090cd4ad50"
      FALLBACK_HOTSPOT_PASSWORD: "JP2dIejjuZTD"
  yamlVersion: !include
    file: ../common/sensors/yamlVersion.yml
    vars:
      YAML_VERSION: "v0.0.9 Jan 30, 2025 17:38"
  heartbeat: !include
    file: ../common/scripts/heartbeat.yml
    vars:
      LED_GPIO: GPIO2
      LED_INVERTED: true

# Enable logging
logger:
  baud_rate: 0
  logs:
    uart: ERROR
    logger: ERROR
    sensor: ERROR
    uart_debug: ERROR
    text_sensor: ERROR
    number: ERROR

###############################
## Switches
###############################
switch:
    ## Allows the silencing of various system alerts. Should default to true.
  - platform: template
    name: "Alerts Enabled"
    id: isAlertsEnabled  
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    pin: GPIO16
    name: "${FRIENDLY_NAME} Feeder"
    id: feeder_${NAME}

  - platform: gpio
    pin: GPIO17
    name: "${FRIENDLY_NAME} Drain Pump"
    id: drain_pump_${NAME}

################
## Scripts
################
script:
  - id: feedPlantsByTime
    mode: single
    then:
      - logger.log:
          format: "${FRIENDLY_NAME}.feedPlantsByTime: Feed cycle initiated feedMistingDuration: %f  feedPauseDuration: %f"
          args: ['id(feedMistingDuration).state', 'id(feedPauseDuration).state']
      - sensor.template.publish:                                                                                                                                           
            id: lastFeedTimestamp                                                                                                                                                   
            state: !lambda 'return id(homeassistant_time).now().timestamp;'
      - switch.turn_on: feeder
      - delay: !lambda "return id(feedMistingDuration).state * 1000;"
      - switch.turn_off: feeder
      - logger.log:
          format: "${FRIENDLY_NAME}.feedPlantsByTime: Feed cycle completed."

##################
## Sensors
##################
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: template
    name: "Last Feed Timestamp"
    id: lastFeedTimestamp   
    device_class: timestamp

########################
## Numbers
########################
number:
  - platform: template
    name: Feed - Misting Duration ## How long to open the feed solenoids for (in seconds)
    id: feedMistingDuration
    min_value: 1
    max_value: 20
    initial_value: 5
    step: .1
    optimistic: true
    mode: BOX
    unit_of_measurement: "duration"
  - platform: template
    name: Feed - Rest Duration ## How long to wait between feed cycles (in seconds)
    id: feedRestDuration
    min_value: 1
    max_value: 3000
    initial_value: 300
    step: 1
    optimistic: true
    mode: BOX       
    unit_of_measurement: "duration"         

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Los_Angeles

text_sensor:
  - platform: template
    name: "Last Feed"
    id: lastFeedTime
    device_class: ""
    lambda: |-
      char str[17];
      time_t currTime = id(lastFeedTimestamp).state; 
      strftime(str, sizeof(str), "%H:%M:%S", localtime(&currTime));
      return  { str }; 

  - platform: template
    name: "Next Feed"
    id: nextFeedTimestamp
    device_class: ""
    lambda: |-
      char str[17];
      time_t currTime = id(lastFeedTimestamp).state + id(feedRestDuration).state; 
      strftime(str, sizeof(str), "%H:%M:%S", localtime(&currTime));
      return  { str };     

  - platform: template
    name: "Current time"
    id: currentTime
    lambda: |-
      char str[17];
      time_t currTime = id(homeassistant_time).now().timestamp;
      strftime(str, sizeof(str), "%H:%M:%S", localtime(&currTime));
      return  { str };
    update_interval: 1000ms

  - platform: template
    name: "Next Feed Countdown"
    id: nextFeedCountdown
    update_interval: 1000ms
    lambda: |-
      auto TAG = "Next Feed Countdown Lambda";    
      // Parse the NextFeedTime string into a usable time.

      std::string str_time = id(nextFeedTimestamp).state; 
      std::tm tm = {};
      std::istringstream ss(str_time);
      std::time_t nextFeedTimestamp = std::mktime(&tm);
      ESP_LOGD(TAG, "Next feed timestamp: %s", str_time );

      // Subtract the NextFeedTime from the current time to get the remaining time.
      //std::time_t duration = nextFeedTimestamp - id(homeassistant_time).now().timestamp;
      std::time_t duration = id(homeassistant_time).now().timestamp;
      char buffer[80];
      strftime(buffer, sizeof(buffer), "%H:%M:%S", std::localtime(&duration));
      return { buffer };

button:
  - platform: template
    id: sendAlertTest
    name: Test Feed Alert
    on_press: 
      then:
        - homeassistant.action:
            action: script.sendalert
            data:
              title: ${FRIENDLY_NAME} TESTING FEED ALERT
            data_template:
              message: "(TESTING) CRITICAL! {{ feedLineNameToken }} measured less than the underfeed alert threshold. Delivered: {{ deliveredAmount }} Underfeed threshold: {{ expectedAmount }}"
            variables:
              feedLineNameToken: return 999;
              deliveredAmount: return 222;
              expectedAmount: return 333;

interval:
  - interval: 1sec
    then:
      - if: 
          condition:
            - lambda: 'return int(id(lastFeedTimestamp).state) < id(homeassistant_time).now().timestamp + int(id(feedRestDuration).state);'
          then:
            - script.execute: feedPlantsByTime
