substitutions:
  NAME: w3l1d
  FRIENDLY_NAME: "W3L1D"

packages:
  device_base: !include
    file: ../../common/boards/esp32S3ModelDCustomPcb.yml
    vars:
      NAME: ${NAME}
      FRIENDLY_NAME: ${FRIENDLY_NAME}
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "ls2WYlAZ1TSlBKczfaIXBy/DcrUv+6kJb3CIvTFipT8="
      OTA_PASSWORD: "1aca097bc1deac0470b36e788e42c878"
      FALLBACK_HOTSPOT_PASSWORD: "JP2dIejjuZTD"

switch:
  - platform: gpio
    pin: GPIO2
    name: "Feed Relay"
    id: "feedRelay"      
  - platform: gpio
    pin: GPIO3
    name: "Drain Relay"
    id: "drainRelay"    

  - platform: template
    name: red
    id: red
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
    on_turn_off:
      then:
      - light.turn_off:
          id: led

  - platform: template
    name: green
    id: green
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0
          green: 100%
          blue: 0
    on_turn_off:
      then:
      - light.turn_off:
          id: led
        


light:
  - platform: neopixelbus
    id: led
    type: GRB
    variant: WS2812
    pin: GPIO48
    num_leds: 1
    name: "NeoPixel Light" 