substitutions:
  lineNumber: "2"
  wallNumber: "2"
  encryptionKey: "XqNcPzUB4vyobdj7Vd765WLQyZTF/86JwF5CXomjWVg="
  otaPassword: "313e3ef0b80c4b7644a540d6b0d947c9"
  fallbackHotspotPassword: "UhtYT6DWw17v"

packages:
  remote_package:
    url: https://github.com/HeathersZen/Aeroponica
    refresh: 0s
    files:
      - esphome/components/SHTxxTempAndHumiditySensor/shtxxTempAndHumiditySensor.yml