substitutions:
  lineNumber: "2"
  wallNumber: "2"
  encryptionKey: "WVRSI3PbGzHt5/06iL7JmvuRE3R4TFNFnT0YiL8Zke4="
  otaPassword: "929a4a4786d9fbf7a959c7238546fa08"
  fallbackHotspotPassword: "UhtYT6DWw17v"

packages:
  remote_package:
    url: https://github.com/HeathersZen/Aeroponica
    refresh: 0s
    files:
      - esphome/components/SHTxxTempAndHumiditySensor/shtxxTempAndHumiditySensor.yml