sensor:
  - platform: resistance
    id: resistanceSensor
    name: "Resistance Level Sensor"
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 831Ohm

# Example source sensor:
  - platform: adc
    id: source_sensor
    pin: 34