sensor:
  - platform: resistance
    id: resistanceSensor
    name: "Resistance Level Sensor"
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 220Ohm
    update_interval: 1s

# Example source sensor:
  - platform: adc
    id: source_sensor
    pin: A0