packages:
  device_base: !include
    file: ../common/boards/esp32DevBoard.yml
    vars:
      NAME: tankfillsensor3
      FRIENDLY_NAME: "Tank Fill Sensor 3"
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "zGWJVJDs88OsGldUdsWIKzXJHTvZZPds2fi4+uMrIOE="
      OTA_PASSWORD: "3ad6cbf585bc8b563f43e21d173f24e8"
      FALLBACK_HOTSPOT_PASSWORD: "JP2dIejjuZTD"
  yamlVersion: !include
    file: ../common/sensors/yamlVersion.yml
    vars:
      YAML_VERSION: "v1.0.1 Jan 18, 2025 22:01"
  heartbeat: !include
    file: ../common/scripts/heartbeat.yml
    vars:
      LED_GPIO: GPIO2
      LED_INVERTED: false
  floatSensor: !include
    file: ./floatSensor.yml

# Enable logging
logger:
  baud_rate: 0
  logs:
    uart: ERROR
    logger: ERROR
    sensor: ERROR
    uart_debug: ERROR
    text_sensor: ERROR
    number: ERROR

number:
  - platform: template
    name: Auto-drain drain stop Percentage
    id: autoDrainStopDrainPercentage
    min_value: 0
    max_value: 80
    initial_value: 0
    step: 1
    optimistic: true
    mode: BOX                                                                                                                                                 
  - platform: template
    name: Auto-fill Filling Stop Percentage
    id: autoFillStopFillPercentage
    min_value: 1
    max_value: 100
    initial_value: 80
    step: 1
    optimistic: true
    mode: BOX