packages:
  device_base: !include
    file: ../common/boards/esp32DevBoard.yml
    vars:
      NAME: tankfillsensor3
      FRIENDLY_NAME: "Tank Fill Sensor 3"
      LOG_LEVEL: DEBUG
      ENCRYPTION_KEY: "zGWJVJDs88OsGldUdsWIKzXJHTvZZPds2fi4+uMrIOE="
      OTA_PASSWORD: "3ad6cbf585bc8b563f43e21d173f24e8"
      FALLBACK_HOTSPOT_PASSWORD: "JP2dIejjuZTD"
  yamlVersion: !include
    file: ../common/sensors/yamlVersion.yml
    vars:
      YAML_VERSION: "v1.0.1 Jan 13, 2025 12:49"
  heartbeat: !include
    file: ../common/scripts/heartbeat.yml
    vars:
      LED_GPIO: GPIO2
      LED_INVERTED: false
  # tof10120Uart: !include
  #   file: ./tof10120Uart.yml
  floatSensor: !include
    file: ./floatSensor.yml

# Enable logging
logger:
  baud_rate: 0
  logs:
    uart: ERROR
    logger: ERROR
    sensor: ERROR
    uart_debug: ERROR
    text_sensor: ERROR
    number: ERROR

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: America/Los_Angeles

number:
  - platform: template
    name: Tank Empty Percentage
    id: tankEmptyPercentage
    min_value: 0
    max_value: 80
    initial_value: 0
    step: 1
    optimistic: true
    mode: BOX
    on_value:
      then:
        - if:
            condition:
            - lambda: 'return id(tankEmptyPercentage).state >= id(tankFullPercentage).state;'
            then:
              - number.set:  
                  id: tankEmptyPercentage                                                                                                                                                   
                  value: 0
  - platform: template
    name: Tank Full Percentage
    id: tankFullPercentage
    min_value: 1
    max_value: 110
    initial_value: 100
    step: 1
    optimistic: true
    mode: BOX
    on_value:
      then:
        - if:
            condition:
            - lambda: 'return id(tankFullPercentage).state <= id(tankEmptyPercentage).state;'
            then:
              - number.set:
                  id: tankFullPercentage                                                                                                                                                   
                  value: 100
      