# Your Wi-Fi SSID and password
wifi_ssid: "FBI Surveilance Van #423"
wifi_password: "alison88"
1ch_relay_ota_password: "0489790b24dadf09eafb249f941b6a76"
1ch_relay_api_key: "Oq/vGvR1OefCHp9gH6zsTEE5kC/9i9GDRg4uNQkn3RE="
ota_password: "dd7adf95aa5a34e92677177dae6487fd"
wifi_ap_password: "alison88"
halogger_password: "9L8fe!MREdRKLa#kc8a7"
